version: '3'
services:
  ms1:
    build: .
    container_name: profiling
    restart: always
    ports:
      - "8080:8080"
      - "7092:7092"
    environment:
      - "JAVA_OPTS=-XX:+PrintFlagsFinal \
                   -XX:+UnlockExperimentalVMOptions \
                   -XX:+UseCGroupMemoryLimitForHeap \
                   -Xms256m \
                   -Xmx256m \
                   -verbose:gc \
                   -XX:-DisableExplicitGC \
                   -XX:HeapDumpPath=./java_pid.hprof \
                   -XX:-HeapDumpOnOutOfMemoryError \
                   -Djava.security.egd=file:/dev/./urandom \
                   -Dcom.sun.management.jmxremote.rmi.port=7092 \
                   -Dcom.sun.management.jmxremote=true \
                   -Dcom.sun.management.jmxremote.port=7092 \
                   -Dcom.sun.management.jmxremote.ssl=false \
                   -Dcom.sun.management.jmxremote.authenticate=false \
                   -Dcom.sun.management.jmxremote.local.only=false \
                   -Djava.rmi.server.hostname=localhost \
                   -Djava.awt.headless=true"
